name: Build APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Berikan izin eksekusi untuk Gradle Wrapper
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Ubah Nama APK
        run: cp app/build/outputs/apk/debug/app-debug.apk KawaiiMusic.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KawaiiMusic-apk
          path: KawaiiMusic.apk

      - name: Buat Rilis Baru
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create "v${{ github.run_number }}" KawaiiMusic.apk --title "Kawaii Music build ${{ github.run_number }}" --notes "APK siap diunduh"
